skyforger/Controllers/HomeController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using skyforger.models.player;

namespace skyforger.Controllers
{
    public class HomeController : Controller
    {
        private readonly PlayersContext _pc;

        public HomeController(PlayersContext pc)
        {
            _pc = pc;
        }
        
        public async Task<IActionResult> Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                string authid = User.FindFirstValue(ClaimTypes.NameIdentifier);
                ViewData["playerdata"] =
                    _pc.Players.FirstOrDefault(t => t.Auth0Id == authid);
            }
            return await Task.FromResult(View());
        }
    }
}

skyforger/Controllers/PlayersController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using skyforger.models.player;

namespace skyforger.Controllers
{
    [ApiController]
    [Authorize]
    [Route("[controller]")]
    public class PlayersController : Controller
    {
        private readonly ILogger<PlayersController> _logger;
        private PlayersContext _pc;
        
        public PlayersController(ILogger<PlayersController> logger, PlayersContext pc)
        {
            _logger = logger;
            _pc = pc;
        }
        
        // GET
        public async Task<IActionResult> Get()
        {
            return await Task.FromResult(Ok());
        }

        [Route("create")]
        public async Task<IActionResult> CreatePlayer([FromForm] Player player)
        {
            try
            {
                player.Auth0Id = User.FindFirstValue(ClaimTypes.NameIdentifier);
                var playerexists = _pc.Players.Any(t => t.Auth0Id == player.Auth0Id);
                if (playerexists)
                {
                    return Ok("Player already exists!");
                }
            
                await _pc.AddAsync(player);
                await _pc.SaveChangesAsync();
            }
            catch (Exception e)
            {
                _logger.LogError("Unable to create player", e);
            }
            
            return Redirect("/");
        }
    }
}

skyforger/Views/Home/Index.cshtml
@model skyforger.models.player.Player
@{
    ViewData["Title"] = "Home Page";
}

<body>
@if (ViewData["playerdata"] == null && User.Identity.IsAuthenticated)
{
    <div class="d-flex justify-content-center">
        @using (Html.BeginForm("CreatePlayer", "Players", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary()
            @Html.Raw("What is your username?")
            @Html.TextBoxFor(t => t.Username, new {@class = "form-control ss-form-entry", @placeholder = "John Snow"})
            @Html.Raw("What is your character's name? (First and last)")
            @Html.TextBoxFor(t => t.CharacterName, new {@class = "form-control ss-form-entry", @placeholder = "Emil Martin"})
            @Html.LabelFor(t => t.ProfilePictureUri)
            @Html.TextBoxFor(t => t.ProfilePictureUri, new {@class = "form-control ss-form-entry"})
            <div class="ss-btn-submit-area">
                <input class="btn btn-primary ss-btn-submit" type="submit" name="submit" value="Submit"/>
            </div>
        }
    </div>
}
</body>