skyforger/Controllers/BackpacksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using skyforger.models.backpacks;
using skyforger.models.player;

namespace skyforger.Controllers
{
    [ApiController]
    [Authorize]
    [Route("[controller]")]
    public class BackpacksController : Controller
    {
        private readonly ILogger<BackpacksController> _logger;
        private PlayersContext _pc;
        private BackpacksContext _bc;
        public BackpacksController(ILogger<BackpacksController> logger, BackpacksContext bc, PlayersContext pc)
        {
            _logger = logger;
            _bc = bc;
            _pc = pc;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            try
            {
                var currentplayer = _pc.Players.FirstOrDefault(t => t.Auth0Id == User.FindFirstValue(ClaimTypes.NameIdentifier));
                ViewData["playerdata"] = currentplayer;
            
                if (currentplayer == null)
                {
                    return Redirect("/");
                }

                var partybackpack = new Player()
                {
                    Username = "Party Backpack",
                    CharacterName = "Party Backpack",
                    ProfilePictureUri = "https://i.imgur.com/L1zjPZv.png"
                };

                var players = _pc.Players.OrderBy(t => t.CharacterName).ToList();
                //put party backpack first so it's rendered first
                players.Insert(0, partybackpack);
            
                ViewData["Backpack"] = _bc.Backpacks.ToList();
                ViewData["Players"] = players;
            }
            catch (Exception e)
            {
                _logger.LogError("Unable to generate backpack index", e);
            }
            
            return await Task.FromResult(View());
        }

        [Route("allitems")]
        public async Task<IActionResult> AllItems()
        {
            var partybackpack = new Player()
            {
                Username = "Party Backpack",
                CharacterName = "Party Backpack",
                ProfilePictureUri = "https://i.imgur.com/L1zjPZv.png"
            };

            ViewData["Player"] = partybackpack;
            ViewData["Backpack"] = _bc.Backpacks.ToList();
            return await Task.FromResult(View());
        }

        [Route("items")]
        public async Task<IActionResult> Items(int id)
        {
            ViewData["Player"] = _pc.Players.FirstOrDefault(t => t.Id == id);
            return await Task.FromResult(View());
        }

        [HttpPost]
        [Route("additems")]
        public async Task<IActionResult> AddItems([FromBody] List<BackpackItem> items)
        {
            return await Task.FromResult(Ok());
        }
    }
}

skyforger/Controllers/ChallengeRatingCalculatorController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace skyforger.Controllers
{
    public class ChallengeRatingCalculatorController : Controller
    {
        private readonly ILogger<ChallengeRatingCalculatorController> _logger;

        public ChallengeRatingCalculatorController(ILogger<ChallengeRatingCalculatorController> logger)
        {
            _logger = logger;
        }
        
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Fetching CR Calc");
            return await Task.FromResult(View());
        }
    }
}

skyforger/Controllers/CharacterController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace skyforger.Controllers
{
    [ApiController]
    [Authorize]
    [Route("[controller]")]
    public class CharacterController : Controller
    {
        private readonly ILogger<CharacterController> _logger;

        public CharacterController(ILogger<CharacterController> logger)
        {
            _logger = logger;
        }
        
        // GET
        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Fetching characters");
            return await Task.FromResult(View());
        }
    }
}

skyforger/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header class="header">
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Skyforger</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Spells" asp-action="Index">Spells</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="Backpacks" asp-action="Index">Backpacks</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-light" asp-area="" asp-controller="ChallengeRatingCalculator" asp-action="Index">CR Calculator</a>
                    </li>
                    @* <li class="nav-item"> *@
                    @*     <a class="nav-link text-light" asp-area="" asp-controller="Character" asp-action="Index">Characters</a> *@
                    @* </li> *@
                </ul>
            </div>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="nav navbar-nav navbar-right">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>
                            <a class="nav-link text-light" id="qsLogoutBtn" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li>
                            <a class="nav-link text-light" id="qsLoginBtn" asp-controller="Account" asp-action="Login">Login</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>